@extends('layouts.app')

@section('title', 'Dashboard')
@section('header', 'Dashboard de Marketing')

@section('content')
@php
    $greeting = now()->hour < 12 ? 'Buenos días' : (now()->hour < 19 ? 'Buenas tardes' : 'Buenas noches');
    $empty = $demoState === 'empty';
@endphp
<div class="mx-auto max-w-[1600px] space-y-8">
    @if($demoState === 'error')
        <x-ui.alert variant="error" class="flex items-start justify-between gap-4"><div><p class="font-semibold">No pudimos cargar tu información</p><p class="mt-1 text-sm">Actualiza la página o inténtalo nuevamente más tarde.</p></div><a href="{{ route('app.dashboard') }}" class="shrink-0 text-sm font-semibold underline">Reintentar</a></x-ui.alert>
    @endif
    <header class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="ds-kicker">Área de Marketing</p><h1 class="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{{ $greeting }}, {{ auth()->user()->name }}</h1><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Aquí tienes un resumen de tus solicitudes creativas.</p></div><a href="{{ route('app.requests.create') }}" class="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-action-primary)] px-5 text-sm font-semibold text-white hover:bg-[var(--color-action-primary-hover)] sm:w-auto"><i data-lucide="plus" class="h-5 w-5" aria-hidden="true"></i>Nueva solicitud</a></header>
    @if($demoState === 'loading')
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Cargando métricas"><x-ui.skeleton class="h-36" /><x-ui.skeleton class="h-36" /><x-ui.skeleton class="h-36" /><x-ui.skeleton class="h-36" /></div><div class="grid gap-8 xl:grid-cols-[1.3fr_.7fr]"><x-ui.skeleton class="h-80" /><x-ui.skeleton class="h-80" /></div>
    @elseif($empty)
        <x-ui.empty-state title="Aún no tienes solicitudes" description="Crea tu primera solicitud para comenzar a colaborar con el equipo creativo." icon="inbox"><a href="{{ route('app.requests.create') }}" class="inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-action-primary)] px-4 text-sm font-semibold">Crear solicitud <i data-lucide="arrow-right" class="h-4 w-4" aria-hidden="true"></i></a></x-ui.empty-state>
    @else
        <x-dashboard.section title="Resumen" description="Una vista rápida del trabajo activo."><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as $metric)<x-dashboard.metric-card :metric="$metric" />@endforeach</div></x-dashboard.section>
        <x-dashboard.section title="Servicios creativos" description="Elige un servicio para iniciar tu próxima solicitud."><div class="grid gap-4 md:grid-cols-3">@foreach($serviceCards as $service)<x-dashboard.service-card :service="$service" />@endforeach</div></x-dashboard.section>
        <div class="grid gap-8 xl:grid-cols-[1.25fr_.75fr]">
            <x-dashboard.section title="Requieren tu atención" description="Prioriza las solicitudes con una acción pendiente."><div class="space-y-3">@forelse($attentionItems as $item)<x-dashboard.attention-item :item="$item" />@empty<x-ui.empty-state title="No tienes solicitudes que requieran atención." description="Te avisaremos cuando haya algo que revisar." icon="check-circle" />@endforelse</div></x-dashboard.section>
            <x-dashboard.section title="Pendientes de revisión" description="Entregables listos para tu aprobación."><div class="space-y-3">@forelse($pendingDeliverables as $deliverable)<x-deliverable.review-card :deliverable="$deliverable" />@empty<x-ui.empty-state title="No tienes entregables pendientes de revisión." icon="check-circle" />@endforelse</div></x-dashboard.section>
        </div>
        <x-dashboard.section title="Solicitudes recientes" description="Consulta el avance de tus solicitudes." :action="null"><div class="mb-4 flex gap-2 overflow-x-auto pb-1" aria-label="Filtros de solicitudes">@foreach(['all' => 'Todas', 'pending' => 'Pendientes', 'in-progress' => 'En proceso', 'review' => 'En revisión', 'completed' => 'Finalizadas'] as $key => $label)<a href="{{ route('app.dashboard', ['filter' => $key]) }}" @class(['inline-flex min-h-10 shrink-0 items-center rounded-[var(--radius-pill)] border px-3 text-xs font-semibold', 'border-[var(--color-action-primary)] bg-[var(--color-action-soft)] text-white' => $filter === $key, 'border-[var(--color-border-default)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)]' => $filter !== $key])>{{ $label }}</a>@endforeach</div><div class="overflow-hidden rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] bg-[var(--color-surface-default)]"><div class="hidden grid-cols-[1.2fr_1fr_1fr_1fr_auto] gap-3 border-b border-[var(--color-border-subtle)] px-3 py-3 text-[11px] font-bold uppercase tracking-wider text-[var(--color-text-tertiary)] lg:grid"><span>Solicitud</span><span>Servicio</span><span>Estado</span><span>Fecha requerida</span><span>Acción</span></div>@forelse($recentRequests as $request)<x-request.list-item :request="$request" />@empty<x-ui.empty-state title="No hay solicitudes en este filtro." description="Prueba con otro filtro para consultar tus solicitudes." />@endforelse</div></x-dashboard.section>
        <div class="grid gap-8 lg:grid-cols-[1fr_1fr]"><x-dashboard.section title="Actividad reciente"><x-ui.card><ol class="relative space-y-0">@foreach($recentActivity as $activity)<x-dashboard.activity-item :activity="$activity" />@endforeach</ol></x-ui.card></x-dashboard.section><x-dashboard.section title="Accesos rápidos"><div class="grid gap-3 sm:grid-cols-2"><x-dashboard.quick-action :href="route('app.requests.create')" icon="plus" title="Nueva solicitud" description="Inicia un brief creativo" /><x-dashboard.quick-action :href="route('app.requests.index')" icon="inbox" title="Ver mis solicitudes" description="Consulta todos tus folios" /><x-dashboard.quick-action :href="route('app.requests.index', ['filter' => 'review'])" icon="search-check" title="Pendientes de revisión" description="Revisa entregables disponibles" /><x-dashboard.quick-action :href="route('app.requests.index', ['filter' => 'drafts'])" icon="file-edit" title="Consultar borradores" description="Continúa un trabajo guardado" /></div></x-dashboard.section></div>
    @endif
</div>
@endsection
