@extends('layouts.app')
@section('title', 'Entregable')
@section('header', 'Entregable')
@section('content')
<div class="mx-auto max-w-6xl space-y-5"><a class="text-sm underline" href="{{ route('app.requests.show', $creativeRequest) }}">← Solicitud</a><h1 class="text-2xl font-bold">{{ $deliverable->title }}</h1><p class="text-sm text-slate-400">{{ $deliverable->status->label() }}</p>
@if($deliverable->currentVersion)<section class="rounded border border-slate-700 bg-slate-900 p-5"><h2 class="text-lg font-semibold">Versión {{ $deliverable->currentVersion->version_number }}</h2><p class="mt-2 whitespace-pre-line text-sm">{{ $deliverable->currentVersion->notes }}</p><ul class="mt-4 space-y-2">@foreach($deliverable->currentVersion->files as $file)<li><a class="underline" href="{{ route('app.requests.deliverables.files.download', [$creativeRequest, $deliverable, $deliverable->currentVersion, $file]) }}">{{ $file->original_name }}</a> · {{ $file->category }}</li>@endforeach</ul>@if($deliverable->status->value === 'marketing_review')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('app.requests.deliverables.approve', [$creativeRequest, $deliverable, $deliverable->currentVersion]) }}">@csrf<input type="hidden" name="confirmed" value="1"><button class="min-h-11 rounded bg-green-700 px-4 text-sm font-semibold">Aprobar entregable</button></form><form method="POST" action="{{ route('app.requests.deliverables.request-corrections', [$creativeRequest, $deliverable, $deliverable->currentVersion]) }}" class="basis-full space-y-2">@csrf<input type="hidden" name="summary" value="Correcciones solicitadas"><textarea required name="details" maxlength="3000" placeholder="Describe las correcciones" class="w-full rounded bg-slate-950 p-3"></textarea><button class="min-h-11 rounded border border-amber-500 px-4 text-sm">Solicitar correcciones</button></form></div>@endif</section>@else<div class="rounded border border-dashed border-slate-700 p-10 text-center">Aún no hay entregables.</div>@endif
<x-comment.thread :commentable="$deliverable" :comments="$deliverable->comments" store-route="app.deliverables.comments.store" reply-route="app.requests.comments.replies.store" :route-parameters="[$creativeRequest, $deliverable]" />
<section class="rounded border border-slate-700 bg-slate-900 p-5"><h2 class="text-lg font-semibold">Historial de versiones</h2><ul class="mt-4 space-y-2">@foreach($deliverable->versions->sortByDesc('version_number') as $version)<li>Versión {{ $version->version_number }} · {{ $version->status->value }} · {{ $version->files->count() }} archivos</li>@endforeach</ul></section></div>
@endsection
