@extends('layouts.design-system')

@section('content')
    <div x-data="{ mobileNav: false }" class="min-h-screen">
        <div class="mx-auto flex max-w-[1600px]">
            <aside class="sticky top-0 hidden h-screen w-64 shrink-0 overflow-y-auto border-r border-[var(--color-border-subtle)] bg-[var(--color-bg-sidebar)] p-5 lg:block">
                <a href="#top" class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-[var(--radius-md)] bg-[var(--color-action-primary)] text-sm font-black">TG</span><span><span class="block text-xs font-black tracking-[.16em]">TOTAL GROUND</span><span class="block text-[11px] text-[var(--color-text-tertiary)]">TG Creative Hub</span></span></a>
                <p class="mt-10 ds-kicker">UI Kit · Fase 2</p>
                <nav class="mt-4 space-y-1 text-sm" aria-label="Secciones del UI Kit">
                    @foreach(['foundation' => 'Fundamentos', 'components' => 'Componentes', 'patterns' => 'Patrones', 'accessibility' => 'Accesibilidad'] as $anchor => $label)
                        <a href="#{{ $anchor }}" class="flex min-h-10 items-center rounded-[var(--radius-md)] px-3 text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white">{{ $label }}</a>
                    @endforeach
                    <div class="my-4 h-px bg-[var(--color-border-subtle)]"></div>
                    @foreach(['colors' => 'Colores', 'type' => 'Tipografía', 'buttons' => 'Botones', 'forms' => 'Formularios', 'statuses' => 'Estados', 'navigation' => 'Navegación', 'data' => 'Datos', 'overlays' => 'Overlays', 'files' => 'Archivos', 'comments' => 'Comentarios', 'wizard' => 'Wizard'] as $anchor => $label)
                        <a href="#{{ $anchor }}" class="block rounded-[var(--radius-md)] px-3 py-2 text-xs text-[var(--color-text-tertiary)] hover:bg-[var(--color-surface-interactive)] hover:text-white">{{ $label }}</a>
                    @endforeach
                </nav>
            </aside>

            <div class="min-w-0 flex-1">
                <header class="sticky top-0 z-[var(--z-sticky)] flex min-h-16 items-center justify-between border-b border-[var(--color-border-subtle)] bg-[rgba(9,11,16,.92)] px-4 backdrop-blur sm:px-8">
                    <button type="button" class="inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] border border-[var(--color-border-default)] px-3 text-sm lg:hidden" @click="mobileNav = !mobileNav" :aria-expanded="mobileNav"><i data-lucide="menu" class="h-4 w-4" aria-hidden="true"></i> Secciones</button>
                    <span class="hidden text-sm text-[var(--color-text-tertiary)] sm:block">Design System / UI Kit</span>
                    <div class="flex items-center gap-2"><x-ui.badge variant="success" icon="check-circle">Local</x-ui.badge><x-ui.icon-button label="Modo presentación" icon="maximize-2" /></div>
                </header>
                <div x-show="mobileNav" x-cloak class="border-b border-[var(--color-border-subtle)] bg-[var(--color-bg-sidebar)] p-4 lg:hidden"><nav class="grid grid-cols-2 gap-1 text-sm">@foreach(['foundation' => 'Fundamentos', 'components' => 'Componentes', 'patterns' => 'Patrones', 'accessibility' => 'Accesibilidad', 'colors' => 'Colores', 'type' => 'Tipografía', 'buttons' => 'Botones', 'forms' => 'Formularios', 'statuses' => 'Estados', 'navigation' => 'Navegación', 'data' => 'Datos', 'overlays' => 'Overlays', 'files' => 'Archivos', 'comments' => 'Comentarios', 'wizard' => 'Wizard'] as $anchor => $label)<a @click="mobileNav = false" href="#{{ $anchor }}" class="rounded px-2 py-2 text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)]">{{ $label }}</a>@endforeach</nav></div>

                <main id="top" class="space-y-20 px-4 py-10 sm:px-8 sm:py-14 xl:px-14">
                    <section class="max-w-4xl"><p class="ds-kicker">TG Creative Hub · Fase 2</p><h1 class="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Un lenguaje visual para<br><span class="text-red-400">trabajo creativo</span></h1><p class="mt-6 max-w-2xl text-base leading-7 text-[var(--color-text-secondary)]">UI Kit local de TOTAL GROUND: componentes sobrios, estados claros y patrones preparados para construir las experiencias de Marketing, Creative y Administración.</p><div class="mt-8 flex flex-wrap gap-3"><x-ui.button variant="primary" @click="document.getElementById('components').scrollIntoView({ behavior: 'smooth' })">Explorar componentes <i data-lucide="arrow-down" class="h-4 w-4" aria-hidden="true"></i></x-ui.button><x-ui.button variant="outline">Ver convenciones</x-ui.button></div></section>

                    <section id="foundation" class="ds-section space-y-8"><div><p class="ds-kicker">01 · Fundamentos</p><h2 class="mt-2 text-2xl font-bold">Una base oscura, precisa y accesible</h2><p class="mt-2 ds-prose">Tokens semánticos preparados para crecer a un tema claro sin acoplar la interfaz a nombres físicos.</p></div>
                        <div id="colors" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Colores</h3><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div class="ds-swatch bg-[var(--color-bg-primary)] p-3"><p class="text-xs font-semibold">Background</p><p class="mt-8 text-[10px] text-[var(--color-text-tertiary)]">#090B10</p></div><div class="ds-swatch bg-[var(--color-surface-default)] p-3"><p class="text-xs font-semibold">Surface</p><p class="mt-8 text-[10px] text-[var(--color-text-tertiary)]">#131924</p></div><div class="ds-swatch bg-[var(--color-surface-elevated)] p-3"><p class="text-xs font-semibold">Elevated</p><p class="mt-8 text-[10px] text-[var(--color-text-tertiary)]">#171E2B</p></div><div class="ds-swatch bg-[var(--color-action-primary)] p-3"><p class="text-xs font-semibold">Action</p><p class="mt-8 text-[10px] text-white/70">#E30613</p></div></div><div class="mt-4 flex flex-wrap gap-2"><x-ui.badge variant="success" icon="check">Éxito</x-ui.badge><x-ui.badge variant="warning" icon="triangle-alert">Advertencia</x-ui.badge><x-ui.badge variant="danger" icon="circle-x">Error</x-ui.badge><x-ui.badge variant="info" icon="info">Información</x-ui.badge><x-ui.badge variant="design">Diseño</x-ui.badge><x-ui.badge variant="video">Video</x-ui.badge><x-ui.badge variant="render">Render 3D</x-ui.badge></div></div>
                        <div id="type" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Tipografía</h3><div class="grid gap-4 rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] bg-[var(--color-surface-default)] p-5 sm:grid-cols-2"><div><p class="text-4xl font-bold">Aa Inter</p><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Fallback local · system-ui</p></div><div class="space-y-2 text-[var(--color-text-secondary)]"><p class="text-2xl font-bold text-white">H2 · 30 / 38 / 700</p><p class="text-base">Body Large · 16 / 26 / 400</p><p class="text-xs uppercase tracking-wider">Caption · 12 / 18 / 400</p></div></div></div>
                        <div class="grid gap-4 sm:grid-cols-3"><x-ui.card><p class="ds-kicker">Espaciado</p><p class="mt-3 text-2xl font-bold">4 · 8 · 12 · 16</p><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Escala base en múltiplos de 4px.</p></x-ui.card><x-ui.card><p class="ds-kicker">Radios</p><p class="mt-3 text-2xl font-bold">6 · 10 · 14 · 16</p><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Pill solo para badges y filtros.</p></x-ui.card><x-ui.card><p class="ds-kicker">Motion</p><p class="mt-3 text-2xl font-bold">120 · 180 · 240ms</p><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Siempre respeta reduced-motion.</p></x-ui.card></div>
                    </section>

                    <section id="components" class="ds-section space-y-8"><div><p class="ds-kicker">02 · Componentes</p><h2 class="mt-2 text-2xl font-bold">Primitivas consistentes</h2></div>
                        <div id="buttons" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Botones</h3><x-ui.card><div class="flex flex-wrap items-center gap-3"><x-ui.button>Primary</x-ui.button><x-ui.button variant="secondary">Secondary</x-ui.button><x-ui.button variant="outline">Outline</x-ui.button><x-ui.button variant="ghost">Ghost</x-ui.button><x-ui.button variant="destructive">Destructive</x-ui.button><x-ui.button variant="link">Link action</x-ui.button><x-ui.icon-button label="Más acciones" icon="more-horizontal" variant="outline" /></div><div class="mt-5 flex flex-wrap items-center gap-3"><x-ui.button size="sm">Small</x-ui.button><x-ui.button size="md">Medium</x-ui.button><x-ui.button size="lg">Large</x-ui.button><x-ui.button loading>Guardando</x-ui.button><x-ui.button disabled>Disabled</x-ui.button></div></x-ui.card></div>
                        <div id="forms" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Formularios</h3><x-ui.card><div class="grid gap-5 md:grid-cols-2"><x-ui.input id="title" label="Título de solicitud" placeholder="Ej. Etiqueta para nueva línea" required hint="Sé específico para facilitar la asignación." icon="text-cursor-input" /><x-ui.input id="email" label="Correo corporativo" value="andrea@totalground.com" type="email" /><x-ui.input id="error" label="Campo con error" value="Fecha inválida" error="Indica una fecha posterior a hoy." /><x-ui.select label="Servicio" required><option>Diseño Gráfico</option><option>Video</option><option>Render 3D</option></x-ui.select><div class="md:col-span-2"><x-ui.textarea label="Brief" placeholder="Describe el objetivo de la pieza..." hint="Máximo recomendado: 500 caracteres." /></div></div><div class="mt-5 flex flex-wrap gap-6 text-sm"><label class="inline-flex items-center gap-2"><input type="checkbox" class="h-4 w-4 accent-red-600"> Enviar copia por correo</label><label class="inline-flex items-center gap-2"><input type="radio" name="priority" class="h-4 w-4 accent-red-600" checked> Prioridad media</label><label class="inline-flex items-center gap-2"><input type="checkbox" class="h-4 w-4 accent-red-600" role="switch"> Activar recordatorio</label></div></x-ui.card></div>
                        <div id="statuses" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Badges y estados</h3><x-ui.card><div class="flex flex-wrap gap-2">@foreach(['Borrador','Pendiente','En validación','Asignada','En proceso','En espera de información','En revisión interna','En revisión de Marketing','Correcciones solicitadas','Aprobada','Finalizada','Cancelada','Rechazada'] as $status)<x-request.status-badge :status="$status" />@endforeach</div><div class="mt-5 flex flex-wrap gap-2"><x-request.priority-badge priority="Baja" /><x-request.priority-badge priority="Media" /><x-request.priority-badge priority="Alta" /><x-request.priority-badge priority="Urgente" /></div><div class="mt-5 flex flex-wrap gap-2"><x-request.service-badge service="Diseño Gráfico" /><x-request.service-badge service="Video" /><x-request.service-badge service="Render 3D" /></div></x-ui.card></div>
                    </section>

                    <section id="patterns" class="ds-section space-y-8"><div><p class="ds-kicker">03 · Patrones</p><h2 class="mt-2 text-2xl font-bold">Patrones para el trabajo diario</h2></div>
                        <div id="navigation" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Navegación</h3><div class="grid overflow-hidden rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] md:grid-cols-[220px_1fr]"><x-navigation.sidebar class="hidden md:block" /><div><x-navigation.topbar /><div class="p-6"><p class="text-sm text-[var(--color-text-secondary)]">Área de contenido con sidebar expandida y topbar.</p><div class="mt-5"><x-ui.tabs :items="['Resumen', 'Actividad', 'Historial']" /></div></div></div></div></div>
                        <div id="data" class="ds-section"><h3 class="mb-4 text-lg font-semibold">Datos, cards y tabla</h3><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-data.stat label="Solicitudes activas" value="24" change="+12% esta semana" icon="inbox" /><x-data.stat label="En revisión" value="08" change="3 requieren acción" icon="eye" /><x-data.stat label="A tiempo" value="92%" change="+4.2% vs. mes anterior" icon="clock-3" /><x-data.stat label="Carga del equipo" value="76%" change="Capacidad saludable" icon="gauge" /></div><div class="mt-5"><x-data.table :headers="['Folio', 'Solicitud', 'Servicio', 'Estado', 'Fecha']"><tr class="hover:bg-[var(--color-surface-interactive)]"><td class="whitespace-nowrap px-4 py-4 font-mono text-xs text-[var(--color-text-secondary)]">TG-00128</td><td class="min-w-52 px-4 py-4 font-semibold">Catálogo de producto A500</td><td class="px-4 py-4"><x-request.service-badge service="Diseño Gráfico" /></td><td class="px-4 py-4"><x-request.status-badge status="En proceso" /></td><td class="whitespace-nowrap px-4 py-4 text-sm text-[var(--color-text-secondary)]">18 Jun 2026</td></tr><tr class="hover:bg-[var(--color-surface-interactive)]"><td class="px-4 py-4 font-mono text-xs text-[var(--color-text-secondary)]">TG-00127</td><td class="px-4 py-4 font-semibold">Video corporativo de seguridad</td><td class="px-4 py-4"><x-request.service-badge service="Video" /></td><td class="px-4 py-4"><x-request.status-badge status="En revisión de Marketing" /></td><td class="px-4 py-4 text-sm text-[var(--color-text-secondary)]">20 Jun 2026</td></tr></x-data.table></div></div>
                        <div class="grid gap-4 md:grid-cols-2"><x-ui.empty-state title="Aún no hay solicitudes" description="Cuando Marketing envíe una solicitud aparecerá aquí." icon="inbox"><x-ui.button size="sm">Nueva solicitud</x-ui.button></x-ui.empty-state><x-ui.card><p class="mb-4 text-sm font-semibold">Estados de carga</p><div class="space-y-3"><x-ui.skeleton class="h-4 w-3/4" /><x-ui.skeleton class="h-4 w-full" /><x-ui.skeleton class="h-10 w-1/2" /><div class="flex items-center gap-2 text-xs text-[var(--color-text-tertiary)]"><x-ui.spinner size="sm" /> Cargando actividad</div></div></x-ui.card></div>
                    </section>

                    <section id="overlays" class="ds-section space-y-8"><div><p class="ds-kicker">04 · Interacción</p><h2 class="mt-2 text-2xl font-bold">Feedback y overlays</h2></div><div class="grid gap-4 md:grid-cols-2"><div class="space-y-3"><x-ui.alert variant="info" title="Información">La fecha operativa será confirmada por el supervisor.</x-ui.alert><x-ui.alert variant="success" title="Guardado correcto">El borrador se guardó hace unos segundos.</x-ui.alert><x-ui.alert variant="warning" title="Revisa la fecha">La fecha solicitada está por debajo del tiempo recomendado.</x-ui.alert><x-ui.alert variant="error" title="No se pudo guardar">Conservamos tus datos. Intenta nuevamente.</x-ui.alert></div><x-ui.card><p class="text-sm font-semibold">Acciones de overlay</p><div class="mt-4 flex flex-wrap gap-3"><x-ui.button variant="outline" @click="$dispatch('open-modal', 'demo-modal')">Abrir modal</x-ui.button><x-ui.button variant="outline" @click="$dispatch('open-drawer', 'demo-drawer')">Abrir drawer</x-ui.button><x-ui.dropdown label="Menú contextual"><button class="block w-full rounded px-3 py-2 text-left text-sm hover:bg-[var(--color-surface-interactive)]">Duplicar</button><button class="block w-full rounded px-3 py-2 text-left text-sm hover:bg-[var(--color-surface-interactive)]">Archivar</button></x-ui.dropdown></div></x-ui.card></div><x-ui.modal name="demo-modal" title="Confirmar acción"><p class="text-sm leading-6 text-[var(--color-text-secondary)]">Esta es una demostración visual. Las acciones de negocio todavía no están conectadas.</p><div class="mt-6 flex justify-end gap-2"><x-ui.button variant="ghost">Cancelar</x-ui.button><x-ui.button>Entendido</x-ui.button></div></x-ui.modal><x-ui.drawer name="demo-drawer" title="Actividad reciente"><p class="text-sm text-[var(--color-text-secondary)]">El drawer conserva el contexto y puede cerrarse con Escape o con el botón de cierre.</p><div class="mt-6"><x-ui.progress value="76" label="Carga del equipo" /></div></x-ui.drawer></section>

                    <section id="files" class="ds-section space-y-4"><div><p class="ds-kicker">05 · Contenido</p><h2 class="mt-2 text-2xl font-bold">Archivos y comentarios</h2></div><div class="grid gap-5 lg:grid-cols-2"><div class="space-y-4"><x-file.upload-zone /><x-file.item name="brief-catalogo-a500.pdf" type="PDF" size="4.8 MB" /><x-file.item name="referencia-empaque.png" type="PNG" size="1.2 MB" final /></div><div id="comments" class="ds-section space-y-4"><x-comment.item>El concepto debe conservar la jerarquía del catálogo y dejar espacio para el precio.</x-comment.item><x-comment.item name="Luis Hernández" role="Diseño Gráfico" time="Hace 4 min" internal edited>Validar con el equipo de impresión antes de enviar la siguiente versión.</x-comment.item><x-ui.textarea label="Añadir comentario" placeholder="Escribe una actualización para el equipo..." /></div></div></section>

                    <section id="wizard" class="ds-section space-y-4"><div><p class="ds-kicker">06 · Wizard</p><h2 class="mt-2 text-2xl font-bold">Progreso sin perder contexto</h2></div><x-ui.card><x-wizard.stepper :steps="['Servicio', 'Plantilla', 'Brief', 'Archivos', 'Revisión']" current="2" /><div class="mt-8 grid gap-5 md:grid-cols-2"><div><p class="text-sm font-semibold">Completa el brief</p><p class="mt-2 text-sm text-[var(--color-text-secondary)]">El guardado automático mantiene tu avance disponible si necesitas salir.</p></div><div class="flex items-center justify-end gap-2"><x-ui.button variant="ghost">Atrás</x-ui.button><x-ui.button>Siguiente <i data-lucide="arrow-right" class="h-4 w-4" aria-hidden="true"></i></x-ui.button></div></div></x-ui.card></section>

                    <section id="accessibility" class="ds-section"><x-ui.alert variant="success" title="Accesibilidad base">Focus visible, labels explícitos, estados con texto e icono, áreas táctiles mínimas de 44px y soporte para prefers-reduced-motion. El contraste debe validarse nuevamente con auditoría automatizada antes de producción.</x-ui.alert></section>
                </main>
            </div>
        </div>
    </div>
                    <section id="kanban" class="ds-section space-y-4"><div><p class="ds-kicker">03.5 · Operación</p><h2 class="mt-2 text-2xl font-bold">Kanban</h2><p class="mt-2 ds-prose">Demostración visual de columnas, tarjetas, prioridad, responsable, fecha, comentarios, archivos y estado vacío. El drag-and-drop es solo demostrativo.</p></div><div class="ui-scrollbar flex gap-4 overflow-x-auto pb-3"><x-request.kanban-column title="Pendientes" count="2" accent="bg-amber-400"><x-request.kanban-card folio="TG-00128" title="Catálogo de producto A500" service="Diseño Gráfico" priority="Alta" person="Andrea Martínez" due="18 Jun" comments="3" files="2" /></x-request.kanban-column><x-request.kanban-column title="En proceso" count="1" accent="bg-blue-400"><x-request.kanban-card folio="TG-00127" title="Video corporativo de seguridad" service="Video" priority="Media" person="Luis Hernández" due="20 Jun" comments="5" files="4" /></x-request.kanban-column><x-request.kanban-column title="Revisión" count="0" accent="bg-violet-400"><x-ui.empty-state title="Sin entregables" description="Las solicitudes listas para revisión aparecerán aquí." icon="eye" class="min-h-40 border-0 bg-transparent px-3 py-6" /></x-request.kanban-column></div></section>
@endsection
