<?php

use App\Http\Controllers\Admin\AuditController as AdminAuditController;
use App\Http\Controllers\Admin\BackupController;
use App\Http\Controllers\Admin\CatalogController as AdminCatalogController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\DepartmentController as AdminDepartmentController;
use App\Http\Controllers\Admin\FailedJobController;
use App\Http\Controllers\Admin\KpiDashboardController;
use App\Http\Controllers\Admin\ReportController as AdminReportController;
use App\Http\Controllers\Admin\ReportExportController as AdminReportExportController;
use App\Http\Controllers\Admin\ReportScheduleController;
use App\Http\Controllers\Admin\RequestController as AdminRequestController;
use App\Http\Controllers\Admin\RequestExportController as AdminRequestExportController;
use App\Http\Controllers\Admin\SavedReportViewController;
use App\Http\Controllers\Admin\SettingsController as AdminSettingsController;
use App\Http\Controllers\Admin\SlaPolicyController;
use App\Http\Controllers\Admin\SystemDashboardController;
use App\Http\Controllers\Admin\UserAccessController as AdminUserAccessController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\UserExportController as AdminUserExportController;
use App\Http\Controllers\Admin\UserStatusController as AdminUserStatusController;
use App\Http\Controllers\App\CommentAttachmentDownloadController as AppCommentAttachmentDownloadController;
use App\Http\Controllers\App\DashboardController;
use App\Http\Controllers\App\DeliverableCommentController as AppDeliverableCommentController;
use App\Http\Controllers\App\DeliverableController as AppDeliverableController;
use App\Http\Controllers\App\DeliverableFileDownloadController as AppDeliverableFileDownloadController;
use App\Http\Controllers\App\DeliverableReviewController as AppDeliverableReviewController;
use App\Http\Controllers\App\DeliverableVersionController as AppDeliverableVersionController;
use App\Http\Controllers\App\DraftController;
use App\Http\Controllers\App\NotificationController as AppNotificationController;
use App\Http\Controllers\App\NotificationPreferenceController as AppNotificationPreferenceController;
use App\Http\Controllers\App\ReportController as AppReportController;
use App\Http\Controllers\App\RequestCancellationController;
use App\Http\Controllers\App\RequestCommentController as AppRequestCommentController;
use App\Http\Controllers\App\RequestController;
use App\Http\Controllers\App\RequestDuplicationController;
use App\Http\Controllers\App\RequestFileController;
use App\Http\Controllers\App\RequestFileDownloadController;
use App\Http\Controllers\App\RequestInformationResponseController;
use App\Http\Controllers\App\RequestSubmissionController;
use App\Http\Controllers\App\RequestWizardController;
use App\Http\Controllers\Creative\CommentAttachmentDownloadController as CreativeCommentAttachmentDownloadController;
use App\Http\Controllers\Creative\DashboardController as CreativeDashboardController;
use App\Http\Controllers\Creative\DeliverableCommentController as CreativeDeliverableCommentController;
use App\Http\Controllers\Creative\DeliverableController as CreativeDeliverableController;
use App\Http\Controllers\Creative\DeliverableFileController;
use App\Http\Controllers\Creative\DeliverableFileDownloadController;
use App\Http\Controllers\Creative\DeliverableInternalNoteController;
use App\Http\Controllers\Creative\DeliverableVersionController as CreativeDeliverableVersionController;
use App\Http\Controllers\Creative\InternalDueDateController;
use App\Http\Controllers\Creative\InternalNoteController;
use App\Http\Controllers\Creative\InternalReviewController;
use App\Http\Controllers\Creative\KanbanController;
use App\Http\Controllers\Creative\MarketingSubmissionController;
use App\Http\Controllers\Creative\NotificationController as CreativeNotificationController;
use App\Http\Controllers\Creative\NotificationPreferenceController as CreativeNotificationPreferenceController;
use App\Http\Controllers\Creative\OperationalPriorityController;
use App\Http\Controllers\Creative\QuickDeliverableController;
use App\Http\Controllers\Creative\ReportController as CreativeReportController;
use App\Http\Controllers\Creative\RequestAssignmentController;
use App\Http\Controllers\Creative\RequestCommentController as CreativeRequestCommentController;
use App\Http\Controllers\Creative\RequestCompletionController;
use App\Http\Controllers\Creative\RequestController as CreativeRequestController;
use App\Http\Controllers\Creative\RequestInformationController;
use App\Http\Controllers\Creative\RequestReassignmentController;
use App\Http\Controllers\Creative\RequestRejectionController;
use App\Http\Controllers\Creative\RequestTransitionController;
use App\Http\Controllers\Creative\RequestValidationController;
use App\Http\Controllers\Creative\WorkloadController;
use App\Http\Controllers\Health\DetailedHealthController;
use App\Http\Controllers\PriorityController;
use App\Http\Controllers\PublicController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PublicController::class, 'home']);
Route::get('/design-system', [PublicController::class, 'designSystem'])->name('design-system.index');

Route::get('/health/details', DetailedHealthController::class)->middleware(['auth', 'active', 'role:admin'])->name('health.details');

Route::middleware(['auth', 'active', 'password.changed'])->group(function (): void {
    Route::get('/priorities', [PriorityController::class, 'index'])->middleware('role:marketing,admin,creative,design,video,render,supervisor')->name('priorities.index');
    Route::post('/priorities/{creativeRequest}/move', [PriorityController::class, 'move'])->middleware('role:admin,creative,design,video,render,supervisor')->name('priorities.move');
    Route::get('/app', DashboardController::class)->middleware('role:marketing,supervisor,admin')->name('app.dashboard');
    Route::middleware('role:marketing,supervisor,admin')->group(function (): void {
        Route::get('/app/requests/create', [RequestWizardController::class, 'create'])->middleware('role:marketing')->name('app.requests.create');
        Route::post('/app/requests', [RequestWizardController::class, 'store'])->middleware('role:marketing')->name('app.requests.store');
        Route::get('/app/requests/drafts', [DraftController::class, 'index'])->middleware('role:marketing')->name('app.requests.drafts.index');
        Route::delete('/app/requests/drafts/{creativeRequest}', [DraftController::class, 'destroy'])->middleware('role:marketing')->name('app.requests.drafts.destroy');
        Route::get('/app/requests/drafts/{creativeRequest}/edit', [RequestWizardController::class, 'edit'])->middleware('role:marketing')->name('app.requests.drafts.edit');
        Route::patch('/app/requests/drafts/{creativeRequest}', [RequestWizardController::class, 'update'])->middleware('role:marketing')->name('app.requests.drafts.update');
        Route::post('/app/requests/drafts/{creativeRequest}/autosave', [RequestWizardController::class, 'autosave'])->middleware('role:marketing')->name('app.requests.drafts.autosave');
        Route::post('/app/requests/drafts/{creativeRequest}/files', [RequestFileController::class, 'store'])->middleware('role:marketing')->name('app.requests.drafts.files.store');
        Route::delete('/app/requests/drafts/{creativeRequest}/files/{file}', [RequestFileController::class, 'destroy'])->middleware('role:marketing')->name('app.requests.drafts.files.destroy');
        Route::post('/app/requests/drafts/{creativeRequest}/submit', [RequestSubmissionController::class, 'submit'])->middleware('role:marketing')->name('app.requests.drafts.submit');
        Route::get('/app/requests/{creativeRequest}/confirmation', [RequestSubmissionController::class, 'confirmation'])->name('app.requests.confirmation');
        Route::post('/app/requests/{creativeRequest}/provide-information', RequestInformationResponseController::class)->middleware('role:marketing')->name('app.requests.provide-information');
        Route::post('/app/requests/{creativeRequest}/comments', [AppRequestCommentController::class, 'store'])->middleware('role:marketing')->name('app.requests.comments.store');
        Route::post('/app/requests/{creativeRequest}/comments/{comment}/replies', [AppRequestCommentController::class, 'reply'])->middleware('role:marketing')->name('app.requests.comments.replies.store');
        Route::patch('/app/requests/{creativeRequest}/comments/{comment}', [AppRequestCommentController::class, 'update'])->middleware('role:marketing')->name('app.requests.comments.update');
        Route::delete('/app/requests/{creativeRequest}/comments/{comment}', [AppRequestCommentController::class, 'destroy'])->middleware('role:marketing')->name('app.requests.comments.destroy');
        Route::get('/app/requests/{creativeRequest}/comments/{comment}/attachments/{attachment}/download', AppCommentAttachmentDownloadController::class)->middleware('role:marketing,admin,supervisor')->name('app.requests.comments.attachments.download');
        Route::get('/app/requests/{creativeRequest}/deliverables', [AppDeliverableController::class, 'index'])->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.index');
        Route::get('/app/requests/{creativeRequest}/deliverables/{deliverable}', [AppDeliverableController::class, 'show'])->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.show');
        Route::get('/app/requests/{creativeRequest}/deliverables/{deliverable}/versions/{version}', [AppDeliverableVersionController::class, 'show'])->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.versions.show');
        Route::get('/app/requests/{creativeRequest}/deliverables/{deliverable}/versions/{version}/files/{file}/download', AppDeliverableFileDownloadController::class)->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.files.download');
        Route::post('/app/requests/{creativeRequest}/deliverables/{deliverable}/versions/{version}/approve', [AppDeliverableReviewController::class, 'approve'])->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.approve');
        Route::post('/app/requests/{creativeRequest}/deliverables/{deliverable}/versions/{version}/request-corrections', [AppDeliverableReviewController::class, 'corrections'])->middleware('role:marketing,admin,supervisor')->name('app.requests.deliverables.request-corrections');
        Route::post('/app/requests/{creativeRequest}/deliverables/{deliverable}/comments', [AppDeliverableCommentController::class, 'store'])->middleware('role:marketing,admin,supervisor')->name('app.deliverables.comments.store');
        Route::get('/app/requests', [RequestController::class, 'index'])->name('app.requests.index');
        Route::get('/app/requests/{creativeRequest}', [RequestController::class, 'show'])->name('app.requests.show');
        Route::get('/app/requests/{creativeRequest}/files/{file}/download', RequestFileDownloadController::class)->name('app.requests.files.download');
        Route::post('/app/requests/{creativeRequest}/duplicate', RequestDuplicationController::class)->name('app.requests.duplicate');
        Route::post('/app/requests/{creativeRequest}/cancel', RequestCancellationController::class)->name('app.requests.cancel');
        Route::view('/app/profile', 'placeholders.app-module')->name('app.profile');
        Route::get('/app/notifications', [AppNotificationController::class, 'index'])->name('app.notifications');
        Route::get('/app/notifications/{notification?}', [AppNotificationController::class, 'index'])->name('app.notifications.index');
        Route::post('/app/notifications/{notification}/read', [AppNotificationController::class, 'read'])->name('app.notifications.read');
        Route::post('/app/notifications/{notification}/unread', [AppNotificationController::class, 'unread'])->name('app.notifications.unread');
        Route::post('/app/notifications/read-all', [AppNotificationController::class, 'readAll'])->name('app.notifications.read-all');
        Route::get('/app/profile/notifications', [AppNotificationPreferenceController::class, 'edit'])->name('app.profile.notifications.edit');
        Route::patch('/app/profile/notifications', [AppNotificationPreferenceController::class, 'update'])->name('app.profile.notifications.update');
        Route::middleware('role:marketing')->group(function (): void {
            Route::get('/app/reports', [AppReportController::class, 'index'])->name('app.reports.index');
            Route::get('/app/reports/requests', [AppReportController::class, 'requests'])->name('app.reports.requests');
        });
    });
    Route::get('/creative', CreativeDashboardController::class)->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.dashboard');
    Route::get('/creative/design', CreativeDashboardController::class)->middleware('role:creative,design,supervisor')->name('creative.design.dashboard');
    Route::get('/creative/video', CreativeDashboardController::class)->middleware('role:creative,video,supervisor')->name('creative.video.dashboard');
    Route::get('/creative/render', CreativeDashboardController::class)->middleware('role:creative,render,supervisor')->name('creative.render.dashboard');
    Route::middleware('role:admin,creative,design,video,render,supervisor')->group(function (): void {
        Route::get('/creative/requests', [CreativeRequestController::class, 'index'])->name('creative.requests.index');
        Route::get('/creative/requests/kanban', KanbanController::class)->name('creative.requests.kanban');
        Route::get('/creative/requests/{creativeRequest}', [CreativeRequestController::class, 'show'])->name('creative.requests.show');
        Route::post('/creative/requests/{creativeRequest}/quick-deliverable', QuickDeliverableController::class)->name('creative.requests.quick-deliverable');
        Route::post('/creative/requests/{creativeRequest}/validate', RequestValidationController::class)->middleware('role:admin,supervisor')->name('creative.requests.validate');
        Route::post('/creative/requests/{creativeRequest}/request-information', RequestInformationController::class)->name('creative.requests.request-information');
        Route::post('/creative/requests/{creativeRequest}/assign', RequestAssignmentController::class)->middleware('role:supervisor')->name('creative.requests.assign');
        Route::post('/creative/requests/{creativeRequest}/reassign', RequestReassignmentController::class)->middleware('role:supervisor')->name('creative.requests.reassign');
        Route::post('/creative/requests/{creativeRequest}/priority', OperationalPriorityController::class)->middleware('role:supervisor')->name('creative.requests.priority');
        Route::post('/creative/requests/{creativeRequest}/internal-date', InternalDueDateController::class)->middleware('role:supervisor')->name('creative.requests.internal-date');
        Route::post('/creative/requests/{creativeRequest}/transition', RequestTransitionController::class)->name('creative.requests.transition');
        Route::post('/creative/requests/{creativeRequest}/reject', RequestRejectionController::class)->middleware('role:supervisor')->name('creative.requests.reject');
        Route::post('/creative/requests/{creativeRequest}/comments', [CreativeRequestCommentController::class, 'store'])->name('creative.requests.comments.store');
        Route::post('/creative/requests/{creativeRequest}/internal-notes', [InternalNoteController::class, 'store'])->name('creative.requests.internal-notes.store');
        Route::post('/creative/requests/{creativeRequest}/comments/{comment}/replies', [CreativeRequestCommentController::class, 'reply'])->name('creative.requests.comments.replies.store');
        Route::patch('/creative/requests/{creativeRequest}/comments/{comment}', [CreativeRequestCommentController::class, 'update'])->name('creative.requests.comments.update');
        Route::delete('/creative/requests/{creativeRequest}/comments/{comment}', [CreativeRequestCommentController::class, 'destroy'])->name('creative.requests.comments.destroy');
        Route::get('/creative/requests/{creativeRequest}/comments/{comment}/attachments/{attachment}/download', CreativeCommentAttachmentDownloadController::class)->name('creative.requests.comments.attachments.download');
        Route::get('/creative/requests/{creativeRequest}/deliverable/{deliverable}', [CreativeDeliverableController::class, 'show'])->name('creative.requests.deliverable.show');
        Route::post('/creative/requests/{creativeRequest}/deliverables', [CreativeDeliverableController::class, 'store'])->name('creative.requests.deliverables.store');
        Route::get('/creative/deliverables/{deliverable}/versions/{version}/edit', [CreativeDeliverableVersionController::class, 'edit'])->name('creative.deliverables.versions.edit');
        Route::patch('/creative/deliverables/{deliverable}/versions/{version}', [CreativeDeliverableVersionController::class, 'update'])->name('creative.deliverables.versions.update');
        Route::post('/creative/deliverables/{deliverable}/versions', [CreativeDeliverableVersionController::class, 'store'])->name('creative.deliverables.versions.store');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/files', [DeliverableFileController::class, 'store'])->name('creative.deliverables.versions.files.store');
        Route::delete('/creative/deliverables/{deliverable}/versions/{version}/files/{file}', [DeliverableFileController::class, 'destroy'])->name('creative.deliverables.versions.files.destroy');
        Route::get('/creative/deliverables/{deliverable}/versions/{version}/files/{file}/download', DeliverableFileDownloadController::class)->name('creative.deliverables.versions.files.download');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/submit-internal', [InternalReviewController::class, 'submit'])->name('creative.deliverables.versions.submit-internal');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/submit-marketing', [InternalReviewController::class, 'submitFinal'])->name('creative.deliverables.versions.submit-marketing');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/internal-approve', [InternalReviewController::class, 'approve'])->middleware('role:admin,supervisor')->name('creative.deliverables.versions.internal-approve');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/internal-changes', [InternalReviewController::class, 'changes'])->middleware('role:admin,supervisor')->name('creative.deliverables.versions.internal-changes');
        Route::post('/creative/deliverables/{deliverable}/versions/{version}/send-marketing', MarketingSubmissionController::class)->middleware('role:admin,supervisor')->name('creative.deliverables.versions.send-marketing');
        Route::post('/creative/requests/{creativeRequest}/complete', RequestCompletionController::class)->middleware('role:admin,supervisor')->name('creative.requests.complete');
        Route::post('/creative/deliverables/{deliverable}/comments', [CreativeDeliverableCommentController::class, 'store'])->name('creative.deliverables.comments.store');
        Route::post('/creative/deliverables/{deliverable}/internal-notes', [DeliverableInternalNoteController::class, 'store'])->name('creative.deliverables.internal-notes.store');
    });
    Route::get('/creative/notifications', [CreativeNotificationController::class, 'index'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.notifications.index');
    Route::post('/creative/notifications/{notification}/read', [CreativeNotificationController::class, 'read'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.notifications.read');
    Route::post('/creative/notifications/{notification}/unread', [CreativeNotificationController::class, 'unread'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.notifications.unread');
    Route::post('/creative/notifications/read-all', [CreativeNotificationController::class, 'readAll'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.notifications.read-all');
    Route::get('/creative/profile/notifications', [CreativeNotificationPreferenceController::class, 'edit'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.profile.notifications.edit');
    Route::patch('/creative/profile/notifications', [CreativeNotificationPreferenceController::class, 'update'])->middleware('role:admin,creative,design,video,render,supervisor')->name('creative.profile.notifications.update');
    Route::get('/creative/workload', WorkloadController::class)->middleware('role:creative,design,video,render,supervisor')->name('creative.workload.index');
    Route::middleware('role:supervisor')->prefix('creative/reports')->name('creative.reports.')->group(function (): void {
        Route::get('/', [CreativeReportController::class, 'operations'])->name('index');
        Route::get('/operations', [CreativeReportController::class, 'operations'])->name('operations');
        Route::get('/workload', [CreativeReportController::class, 'workload'])->name('workload');
        Route::get('/sla', [CreativeReportController::class, 'sla'])->name('sla');
    });
    Route::get('/creative/my-metrics', [CreativeReportController::class, 'mine'])->middleware('role:creative,design,video,render')->name('creative.metrics.mine');
    Route::middleware('role:admin')->prefix('admin')->name('admin.')->group(function (): void {
        Route::get('/', AdminDashboardController::class)->name('dashboard');
        Route::get('/kpis', KpiDashboardController::class)->name('kpis.index');
        Route::get('/users', [AdminUserController::class, 'index'])->name('users.index');
        Route::get('/users/create', [AdminUserController::class, 'create'])->name('users.create');
        Route::post('/users', [AdminUserController::class, 'store'])->middleware('throttle:10,1')->name('users.store');
        Route::get('/users/{user}', [AdminUserController::class, 'show'])->name('users.show');
        Route::get('/users/{user}/edit', [AdminUserController::class, 'edit'])->name('users.edit');
        Route::patch('/users/{user}', [AdminUserController::class, 'update'])->middleware('password.confirm')->name('users.update');
        Route::post('/users/{user}/activate', [AdminUserStatusController::class, 'activate'])->middleware('throttle:20,1')->name('users.activate');
        Route::post('/users/{user}/deactivate', [AdminUserStatusController::class, 'deactivate'])->middleware(['password.confirm', 'throttle:20,1'])->name('users.deactivate');
        Route::post('/users/{user}/suspend', [AdminUserStatusController::class, 'suspend'])->middleware(['password.confirm', 'throttle:20,1'])->name('users.suspend');
        Route::post('/users/{user}/restore-access', [AdminUserStatusController::class, 'restore'])->middleware('throttle:20,1')->name('users.restore-access');
        Route::post('/users/{user}/send-password-reset', [AdminUserAccessController::class, 'reset'])->middleware(['password.confirm', 'throttle:5,60'])->name('users.send-password-reset');
        Route::get('/departments', [AdminDepartmentController::class, 'index'])->name('departments.index');
        Route::get('/departments/create', [AdminDepartmentController::class, 'create'])->name('departments.create');
        Route::post('/departments', [AdminDepartmentController::class, 'store'])->name('departments.store');
        Route::get('/departments/{department}/edit', [AdminDepartmentController::class, 'edit'])->name('departments.edit');
        Route::patch('/departments/{department}', [AdminDepartmentController::class, 'update'])->name('departments.update');
        Route::post('/departments/{department}/activate', [AdminDepartmentController::class, 'activate'])->name('departments.activate');
        Route::post('/departments/{department}/deactivate', [AdminDepartmentController::class, 'deactivate'])->name('departments.deactivate');
        Route::get('/catalogs', [AdminCatalogController::class, 'index'])->name('catalogs.index');
        Route::get('/catalogs/request-types', [AdminCatalogController::class, 'index'])->name('catalogs.request-types.index');
        Route::post('/catalogs/request-types', [AdminCatalogController::class, 'store'])->name('catalogs.request-types.store');
        Route::patch('/catalogs/request-types/{requestType}', [AdminCatalogController::class, 'update'])->name('catalogs.request-types.update');
        Route::post('/catalogs/request-types/{requestType}/activate', [AdminCatalogController::class, 'activate'])->name('catalogs.request-types.activate');
        Route::post('/catalogs/request-types/{requestType}/deactivate', [AdminCatalogController::class, 'deactivate'])->name('catalogs.request-types.deactivate');
        Route::get('/settings', [AdminSettingsController::class, 'index'])->name('settings.index');
        Route::patch('/settings', [AdminSettingsController::class, 'update'])->middleware(['password.confirm', 'throttle:20,1'])->name('settings.update');
        Route::get('/requests', [AdminRequestController::class, 'index'])->name('requests.index');
        Route::get('/requests/{creativeRequest}', [AdminRequestController::class, 'show'])->name('requests.show');
        Route::get('/audit', [AdminAuditController::class, 'index'])->name('audit.index');
        Route::get('/exports/users', AdminUserExportController::class)->middleware(['password.confirm', 'throttle:5,60'])->name('exports.users');
        Route::get('/exports/requests', AdminRequestExportController::class)->middleware(['password.confirm', 'throttle:5,60'])->name('exports.requests');
        Route::prefix('system')->name('system.')->group(function (): void {
            Route::get('/', [SystemDashboardController::class, 'index'])->name('index');
            Route::get('/jobs', [SystemDashboardController::class, 'jobs'])->name('jobs.index');
            Route::post('/jobs/{uuid}/retry', [FailedJobController::class, 'retry'])->middleware(['password.confirm', 'throttle:10,60'])->name('jobs.retry');
            Route::post('/jobs/{uuid}/forget', [FailedJobController::class, 'forget'])->middleware(['password.confirm', 'throttle:10,60'])->name('jobs.forget');
            Route::get('/backups', [BackupController::class, 'index'])->name('backups.index');
            Route::post('/backups', [BackupController::class, 'store'])->middleware(['password.confirm', 'throttle:5,60'])->name('backups.store');
            Route::post('/backups/{backup}/verify', [BackupController::class, 'verify'])->where('backup', '.*')->middleware('throttle:10,60')->name('backups.verify');
        });
        Route::middleware('throttle:60,1')->prefix('reports')->name('reports.')->group(function (): void {
            Route::get('/', [AdminReportController::class, 'index'])->name('index');
            Route::get('/executive', [AdminReportController::class, 'executive'])->name('executive');
            Route::get('/operations', [AdminReportController::class, 'operations'])->name('operations');
            Route::get('/requests', [AdminReportController::class, 'requests'])->name('requests');
            Route::get('/deliverables', [AdminReportController::class, 'deliverables'])->name('deliverables');
            Route::get('/corrections', [AdminReportController::class, 'corrections'])->name('corrections');
            Route::get('/sla', [AdminReportController::class, 'sla'])->name('sla');
            Route::get('/sla/policies', [SlaPolicyController::class, 'index'])->name('sla.policies.index');
            Route::post('/sla/policies', [SlaPolicyController::class, 'store'])->name('sla.policies.store');
            Route::patch('/sla/policies/{slaPolicy}', [SlaPolicyController::class, 'update'])->name('sla.policies.update');
            Route::post('/sla/policies/{slaPolicy}/toggle', [SlaPolicyController::class, 'toggle'])->name('sla.policies.toggle');
            Route::get('/workload', [AdminReportController::class, 'workload'])->name('workload');
            Route::get('/export/csv', [AdminReportExportController::class, 'csv'])->middleware('throttle:10,60')->name('export.csv');
            Route::get('/export/pdf', [AdminReportExportController::class, 'pdf'])->middleware('throttle:5,60')->name('export.pdf');
            Route::get('/saved-views', [SavedReportViewController::class, 'index'])->name('saved-views.index');
            Route::post('/saved-views', [SavedReportViewController::class, 'store'])->middleware('throttle:20,1')->name('saved-views.store');
            Route::patch('/saved-views/{savedView}', [SavedReportViewController::class, 'update'])->middleware('throttle:20,1')->name('saved-views.update');
            Route::delete('/saved-views/{savedView}', [SavedReportViewController::class, 'destroy'])->middleware('throttle:20,1')->name('saved-views.destroy');
            Route::get('/schedules', [ReportScheduleController::class, 'index'])->name('schedules.index');
            Route::post('/schedules', [ReportScheduleController::class, 'store'])->middleware('throttle:10,60')->name('schedules.store');
            Route::patch('/schedules/{reportSchedule}', [ReportScheduleController::class, 'update'])->name('schedules.update');
            Route::post('/schedules/{reportSchedule}/activate', [ReportScheduleController::class, 'activate'])->name('schedules.activate');
            Route::post('/schedules/{reportSchedule}/deactivate', [ReportScheduleController::class, 'deactivate'])->name('schedules.deactivate');
        });
    });
});

require __DIR__.'/auth.php';
