@extends('layouts.app')

@section('title', 'Mis solicitudes')
@section('header', 'Mis solicitudes')

@section('content')
<div class="mx-auto max-w-[1600px] space-y-6"><span class="sr-only">Módulo en construcción</span>
    @if(request('demo') === 'error')<x-ui.alert variant="error"><strong>No pudimos cargar tus solicitudes.</strong><p class="mt-1 text-sm">Actualiza la página o inténtalo nuevamente más tarde.</p><a href="{{ route('app.requests.index') }}" class="mt-2 inline-block text-sm font-semibold underline">Reintentar</a></x-ui.alert>@endif
    @if(request('demo') === 'loading')<div class="grid gap-4" aria-label="Cargando solicitudes"><x-ui.skeleton class="h-16" /><x-ui.skeleton class="h-16" /><x-ui.skeleton class="h-16" /></div>@endif
    <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="ds-kicker">Seguimiento creativo</p><h1 class="mt-2 text-2xl font-bold">Mis solicitudes</h1><p class="mt-2 text-sm text-[var(--color-text-secondary)]">Consulta y da seguimiento a tus solicitudes creativas.</p></div><a href="{{ route('app.requests.create') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-action-primary)] px-4 text-sm font-semibold">Nueva solicitud</a></header>
    <div class="grid grid-cols-2 gap-3 md:grid-cols-5" aria-label="Resumen de solicitudes">
        @foreach(['all' => 'Todas', 'draft' => 'Borradores', 'active' => 'Activas', 'review' => 'En revisión', 'completed' => 'Finalizadas'] as $key => $label)
            <a href="{{ route('app.requests.index', $key === 'all' ? [] : ['status' => $key === 'draft' ? 'draft' : ($key === 'review' ? 'marketing_review' : null)]) }}" class="rounded-[var(--radius-card)] border p-4 {{ (($filters['status'] ?? null) === ($key === 'draft' ? 'draft' : ($key === 'review' ? 'marketing_review' : null)) || ($key === 'all' && empty($filters['status']))) ? 'border-[var(--color-action-primary)] bg-[var(--color-action-soft)]' : 'border-[var(--color-border-subtle)] bg-[var(--color-surface-default)]' }}"><span class="block text-xs text-[var(--color-text-tertiary)]">{{ $label }}</span><strong class="mt-2 block text-2xl">{{ $metrics[$key] }}</strong></a>
        @endforeach
    </div>
    <form method="GET" class="rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] bg-[var(--color-surface-default)] p-4" aria-label="Buscar y filtrar solicitudes">
        <div class="grid gap-3 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><label class="block md:col-span-1"><span class="text-xs font-semibold">Buscar</span><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Buscar por folio o título" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-3 text-sm"></label><label class="block"><span class="text-xs font-semibold">Estado</span><select name="status" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-3 text-sm"><option value="">Todos</option>@foreach(\App\Enums\RequestStatus::cases() as $status)<option value="{{ $status->value }}" @selected(($filters['status'] ?? '') === $status->value)>{{ $status->label() }}</option>@endforeach</select></label><label class="block"><span class="text-xs font-semibold">Servicio</span><select name="service" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-3 text-sm"><option value="">Todos</option>@foreach(\App\Enums\CreativeService::cases() as $service)<option value="{{ $service->value }}" @selected(($filters['service'] ?? '') === $service->value)>{{ $service->label() }}</option>@endforeach</select></label><label class="block"><span class="text-xs font-semibold">Prioridad</span><select name="priority" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-3 text-sm"><option value="">Todas</option>@foreach(\App\Enums\RequestPriority::cases() as $priority)<option value="{{ $priority->value }}" @selected(($filters['priority'] ?? '') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></label><button class="mt-auto min-h-11 rounded-[var(--radius-md)] bg-[var(--color-action-primary)] px-4 text-sm font-semibold">Buscar</button></div>
        <div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label class="text-xs">Fecha requerida desde<input type="date" name="required_from" value="{{ $filters['required_from'] ?? '' }}" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-2"></label><label class="text-xs">Fecha requerida hasta<input type="date" name="required_to" value="{{ $filters['required_to'] ?? '' }}" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-2"></label><label class="text-xs">Ordenar<select name="sort" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-2"><option value="updated_at">Última actualización</option><option value="created_at">Más recientes</option><option value="required_date">Fecha requerida próxima</option><option value="requested_priority">Prioridad</option></select></label><label class="text-xs">Por página<select name="per_page" class="mt-1 w-full rounded-[var(--radius-md)] bg-[var(--color-bg-primary)] px-3 py-2"><option>10</option><option>25</option><option>50</option></select></label></div>
        <div class="mt-3 flex flex-wrap items-center gap-3 text-sm"><label class="inline-flex items-center gap-2"><input type="checkbox" name="attention" value="1" @checked(!empty($filters['attention']))> Requieren atención</label><label class="inline-flex items-center gap-2"><input type="checkbox" name="drafts" value="1" @checked(!empty($filters['drafts']))> Solo borradores</label><a href="{{ route('app.requests.index') }}" class="font-semibold underline">Limpiar filtros</a></div>
    </form>
    <div class="flex items-center justify-between text-sm text-[var(--color-text-secondary)]"><span>{{ $requests->total() }} resultados · mostrando {{ $requests->firstItem() ?? 0 }}–{{ $requests->lastItem() ?? 0 }}</span></div>
    @if($requests->isEmpty())<x-ui.empty-state title="{{ request()->hasAny(['q','status','service','priority','attention','drafts']) ? 'No encontramos solicitudes' : 'Aún no tienes solicitudes' }}" description="{{ request()->hasAny(['q','status','service','priority','attention','drafts']) ? 'Prueba ajustando los filtros o la búsqueda.' : 'Crea tu primera solicitud para comenzar a colaborar con el equipo creativo.' }}" icon="inbox"><a href="{{ route('app.requests.create') }}" class="font-semibold underline">Nueva solicitud</a></x-ui.empty-state>@else
    <div class="hidden overflow-x-auto rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] lg:block"><table class="w-full text-left text-sm"><caption class="sr-only">Listado de mis solicitudes creativas</caption><thead class="bg-[var(--color-surface-default)] text-xs text-[var(--color-text-tertiary)]"><tr><th scope="col" class="p-4">Folio</th><th scope="col" class="p-4">Solicitud</th><th scope="col" class="p-4">Servicio</th><th scope="col" class="p-4">Estado</th><th scope="col" class="p-4">Prioridad</th><th scope="col" class="p-4">Fecha requerida</th><th scope="col" class="p-4">Actualización</th><th scope="col" class="p-4">Acciones</th></tr></thead><tbody>@foreach($requests as $item)<tr class="border-t border-[var(--color-border-subtle)]"><td class="p-4 font-mono text-xs"><a class="underline" href="{{ route('app.requests.show', $item) }}">{{ $item->folio }}</a></td><td class="p-4 font-semibold">{{ $item->title ?: 'Sin título' }}</td><td class="p-4">{{ $item->service->label() }}</td><td class="p-4">{{ $item->status->label() }}</td><td class="p-4">{{ $item->requested_priority->label() }}</td><td class="p-4">{{ $item->required_date?->isoFormat('D MMM YYYY') ?? 'Sin fecha' }}</td><td class="p-4 text-xs text-[var(--color-text-secondary)]">{{ $item->updated_at->diffForHumans() }}</td><td class="p-4"><a class="underline" href="{{ route('app.requests.show', $item) }}">Ver</a>@if($item->isDraft()) · <a class="underline" href="{{ route('app.requests.drafts.edit', $item) }}">Retomar</a>@endif</td></tr>@endforeach</tbody></table></div>
    <div class="space-y-3 lg:hidden">@foreach($requests as $item)<article class="rounded-[var(--radius-card)] border border-[var(--color-border-subtle)] bg-[var(--color-surface-default)] p-4"><div class="flex items-start justify-between gap-3"><div><a href="{{ route('app.requests.show', $item) }}" class="font-mono text-xs underline">{{ $item->folio }}</a><h2 class="mt-1 font-semibold">{{ $item->title ?: 'Sin título' }}</h2></div><span class="text-xs">{{ $item->status->label() }}</span></div><p class="mt-3 text-sm text-[var(--color-text-secondary)]">{{ $item->service->label() }} · {{ $item->requested_priority->label() }}</p><p class="mt-2 text-xs text-[var(--color-text-tertiary)]">Fecha requerida: {{ $item->required_date?->isoFormat('D MMM YYYY') ?? 'Sin fecha' }} · {{ $item->updated_at->diffForHumans() }}</p><div class="mt-4 flex gap-3 text-sm font-semibold"><a href="{{ route('app.requests.show', $item) }}">Ver solicitud</a>@if($item->isDraft())<a href="{{ route('app.requests.drafts.edit', $item) }}">Retomar</a>@endif</div></article>@endforeach</div>
    @endif
    <div>{{ $requests->links() }}</div>
</div>
@endsection
