<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="description" content="Dashboard de Marketing de TG Creative Hub">
        <title>@yield('title', 'Dashboard') · TG Creative Hub</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="min-h-screen bg-[var(--color-bg-primary)] text-white antialiased" x-data="{ sidebarOpen: false, userMenuOpen: false, notificationsOpen: false }" @keydown.escape="sidebarOpen = false; userMenuOpen = false; notificationsOpen = false">
        <a href="#main-content" class="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[var(--z-modal)] focus:rounded-[var(--radius-md)] focus:bg-[var(--color-action-primary)] focus:px-4 focus:py-3">Saltar al contenido principal</a>
        <div class="flex min-h-screen">
            <div x-show="sidebarOpen" x-cloak @click="sidebarOpen = false" class="fixed inset-0 z-30 bg-black/60 lg:hidden" aria-hidden="true"></div>
            <aside class="fixed inset-y-0 left-0 z-40 flex w-72 -translate-x-full flex-col border-r border-[var(--color-border-subtle)] bg-[var(--color-bg-sidebar)] p-4 transition-transform duration-200 lg:static lg:translate-x-0 lg:w-64" :class="sidebarOpen ? 'translate-x-0' : ''" aria-label="Navegación principal">
                <div class="flex items-center justify-between px-2 py-3">
                    <a href="{{ route('app.dashboard') }}" class="flex items-center gap-3" aria-label="Ir al inicio de TG Creative Hub"><span class="flex h-9 w-9 items-center justify-center rounded-[var(--radius-md)] bg-[var(--color-action-primary)] text-sm font-black">TG</span><span><span class="block text-xs font-black tracking-[.16em]">TOTAL GROUND</span><span class="block text-[11px] text-[var(--color-text-tertiary)]">TG Creative Hub</span></span></a>
                    <button type="button" @click="sidebarOpen = false" class="inline-flex min-h-11 min-w-11 items-center justify-center rounded-[var(--radius-md)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] lg:hidden" aria-label="Cerrar menú"><i data-lucide="x" class="h-5 w-5" aria-hidden="true"></i></button>
                </div>
                <nav class="mt-8 space-y-1" aria-label="Navegación de Marketing">
                    <a href="{{ route('app.dashboard') }}" aria-current="page" class="flex min-h-11 items-center gap-3 rounded-[var(--radius-md)] bg-[var(--color-action-soft)] px-3 text-sm font-semibold text-white"><i data-lucide="layout-dashboard" class="h-5 w-5" aria-hidden="true"></i>Inicio</a>
                    <a href="{{ route('app.requests.create') }}" class="flex min-h-11 items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white"><i data-lucide="plus" class="h-5 w-5" aria-hidden="true"></i>Nueva solicitud</a>
                    <a href="{{ route('app.requests.index') }}" class="flex min-h-11 items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white"><i data-lucide="inbox" class="h-5 w-5" aria-hidden="true"></i>Mis solicitudes</a>
                </nav>
                <div class="my-6 border-t border-[var(--color-border-subtle)]"></div>
                <nav class="space-y-1" aria-label="Navegación secundaria">
                    <a href="{{ route('app.notifications') }}" class="flex min-h-11 items-center justify-between gap-3 rounded-[var(--radius-md)] px-3 text-sm text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white"><span class="flex items-center gap-3"><i data-lucide="bell" class="h-5 w-5" aria-hidden="true"></i>Notificaciones</span><x-ui.badge variant="neutral" size="sm">Próximamente</x-ui.badge></a>
                    <a href="{{ route('app.profile') }}" class="flex min-h-11 items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white"><i data-lucide="user-check" class="h-5 w-5" aria-hidden="true"></i>Mi perfil</a>
                </nav>
                <div class="mt-auto border-t border-[var(--color-border-subtle)] pt-4">
                    <div class="flex items-center gap-3 px-2 py-3"><x-ui.avatar :name="auth()->user()->name" size="sm" status="online" /><div class="min-w-0"><p class="truncate text-sm font-semibold">{{ auth()->user()->name }}</p><p class="text-xs capitalize text-[var(--color-text-tertiary)]">{{ auth()->user()->role->value }}</p></div></div>
                    <form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="flex min-h-11 w-full items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] hover:text-white"><i data-lucide="log-out" class="h-5 w-5" aria-hidden="true"></i>Cerrar sesión</button></form>
                </div>
            </aside>
            <div class="flex min-w-0 flex-1 flex-col">
                <header class="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-[var(--color-border-subtle)] bg-[var(--color-bg-secondary)]/95 px-4 backdrop-blur sm:px-6">
                    <div class="flex min-w-0 items-center gap-3"><button type="button" @click="sidebarOpen = true" class="inline-flex min-h-11 min-w-11 items-center justify-center rounded-[var(--radius-md)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)] lg:hidden" aria-label="Abrir menú"><i data-lucide="menu" class="h-5 w-5" aria-hidden="true"></i></button><div class="min-w-0"><p class="truncate text-sm font-semibold">@yield('header', 'Dashboard de Marketing')</p><p class="hidden text-xs text-[var(--color-text-tertiary)] sm:block">Inicio / Marketing</p></div></div>
                    <div class="relative flex items-center gap-2"><button type="button" disabled class="inline-flex min-h-11 min-w-11 items-center justify-center rounded-[var(--radius-md)] text-[var(--color-text-tertiary)] opacity-60" aria-label="Búsqueda próximamente"><i data-lucide="search" class="h-5 w-5" aria-hidden="true"></i></button><button type="button" @click="notificationsOpen = !notificationsOpen" :aria-expanded="notificationsOpen" class="relative inline-flex min-h-11 min-w-11 items-center justify-center rounded-[var(--radius-md)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-interactive)]" aria-label="Abrir notificaciones"><i data-lucide="bell" class="h-5 w-5" aria-hidden="true"></i><span class="absolute right-2 top-2 h-2 w-2 rounded-full bg-[var(--color-action-primary)]" aria-label="Hay novedades"></span></button><div class="relative"><button type="button" @click="userMenuOpen = !userMenuOpen" :aria-expanded="userMenuOpen" class="flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] px-2 hover:bg-[var(--color-surface-interactive)]" aria-label="Abrir menú de usuario"><x-ui.avatar :name="auth()->user()->name" size="sm" /><i data-lucide="chevron-down" class="hidden h-4 w-4 text-[var(--color-text-tertiary)] sm:block" aria-hidden="true"></i></button><div x-show="userMenuOpen" x-cloak @click.outside="userMenuOpen = false" class="absolute right-0 z-50 mt-2 w-52 rounded-[var(--radius-md)] border border-[var(--color-border-default)] bg-[var(--color-surface-elevated)] p-1 shadow-[var(--shadow-md)]"><a href="{{ route('app.profile') }}" class="flex min-h-11 items-center gap-2 rounded-[var(--radius-sm)] px-3 text-sm hover:bg-[var(--color-surface-interactive)]">Mi perfil</a><a href="{{ route('app.profile') }}" class="flex min-h-11 items-center gap-2 rounded-[var(--radius-sm)] px-3 text-sm hover:bg-[var(--color-surface-interactive)]">Configuración de cuenta</a><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="flex min-h-11 w-full items-center rounded-[var(--radius-sm)] px-3 text-left text-sm text-red-300 hover:bg-[var(--color-surface-interactive)]">Cerrar sesión</button></form></div></div></div>
                    <div x-show="notificationsOpen" x-cloak @click.outside="notificationsOpen = false" class="absolute right-4 top-14 z-50 w-[min(22rem,calc(100vw-2rem))] rounded-[var(--radius-md)] border border-[var(--color-border-default)] bg-[var(--color-surface-elevated)] p-4 shadow-[var(--shadow-md)]"><div class="flex items-center justify-between"><h2 class="font-semibold">Notificaciones</h2><x-ui.badge variant="neutral" size="sm">Demo</x-ui.badge></div><p class="mt-3 text-sm text-[var(--color-text-secondary)]">El centro de notificaciones estará disponible próximamente.</p></div>
                </header>
                <main id="main-content" class="flex-1 px-4 py-6 sm:px-6 lg:px-8" tabindex="-1">@if(session('status'))<x-ui.alert variant="success" class="mb-6">{{ session('status') }}</x-ui.alert>@endif @yield('content')</main>
            </div>
        </div>
    </body>
</html>
